### ISSUE TITLE
I am not able to remove and readd an item from itemsInArea

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/isodom.js#12]
Hey Razr, 

I just wanted to readd an item, which I got from `itemsInArea`. Maybe you just could take a look and tell me, what I do wrong..

```javascript
    // Change Savegame Entry
    const gridEntry = $rootScope.settings.office.grid.find((gridCell) => gridCell.workstationId && gridCell.workstationId === selectedWorkstation.id);
    gridEntry.itemName = workstationTypeName;

    // Remove Item from Grid

    const isoDomItems = iso.itemsInArea();
    const isoDomItem = isoDomItems.find(x => x.item.workstationId === selectedWorkstation.id);

    //isoDomItem is defined at this point.
    iso.removeItem(isoDomItem.item);

    // Add Item to Grid
    iso.addItem(isoDomItem.item, gridEntry.x, gridEntry.y);

```
Afterwards I see this.
![image](https://user-images.githubusercontent.com/12380026/32634742-59c6e9b2-c5ad-11e7-9323-86a5b9f92e67.png)

Best Greetings, 
    Johann

**Comment by jhovgaard** [comment]
You'll need to create a new IsodomItem object, the old one can't be reused (probably because it contains the original DOM element).

`
 iso.addItem(new IsoDomItem(isoDomItem.item.name), gridEntry.x, gridEntry.y); 
`

Should work instead.

**Comment by donnysim** [comment]
After adding a new item IsoDom.draw should be called to position the image and calculate it's index. Readding same item should be possible (if not, it's probably a logic bug).

If your moving it, you can call moveItem.

**Comment by donnysim** [comment]
Calling draw manually is for performance situations where you'd want to add multiple items before calculating.

**Comment by johannwagner** [comment]
Thanks for your input, I will verify this in some hours !

**Comment by donnysim** [comment]
There was a "bug" that prevented remounting, fixed.
