### ISSUE TITLE
Define roadmap and goals

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/isodom.js#2]

**Comment by jhovgaard** [comment]
I've created a set of initial issues. Let's discuss in each individual issue instead.

**Comment by InDieTasten** [comment]
I really think we should design the interface in it's entirety first. Making everything individually just scrumbles everything together in a weird way. Creating an open framework requires many decisions on the interface @jhovgaard, and to make it useful for anybody else other than you will be very difficult later on, if we start "add a function here, adding another function here, and doing that here, and 2 weeks later a similar function needs to be added, that does almost the same way but not quite". code quality, and therefor it's value goes down when working like this.
I know, that @jhovgaard doesn't like that approach, but it's very important when dealing with code that is going to be used by other people.

**Comment by jhovgaard** [comment]
@InDieTasten No no, I'm not against this approach at all. Basically it's a public "contract" for the API/framework. Makes sense to start out with that.

**Comment by InDieTasten** [comment]
## Outcome:

must have:
    isometric view
    zoom
    scrolling
    absolute positioning thats not constrained to tiles
    mouse support


nice to have:
    elevation / 3 dimensions
    rotation
    add dom elements to render instead of images

v2:
    (rendering concave shapes)
    (infinite world)
