### ISSUE TITLE
Public Method: Move Object

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/isodom.js#5]
Public method that allows you to move an existing object on the grid.

Once executed the object should be shown with 50% opacity. When the player clicks on a new cell the object will moved to this location. While moving the object no changes should be made to the "inventory". We want the player to be able to refresh the browser in the middle of a move-operation, without messing up the grid.

If the player clicks `Right Mouse Button` or press `R` a rotate event will happen rotating the object 90 degrees. In Developer Tycoon these are called orientation 1-4. 

A public method for cancelling the operation should be added to. Pressing `ESC` while in moving-mode should also cancel the operation.

**Comment by InDieTasten** [comment]
Concrete behavior will not be added into isodom.js.

The desired behavior will as well be possible through our well designed public interface.
