### ISSUE TITLE
Lockable cells

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/isodom.js#7]
We need to make a system allowing you to lock specific cells. 

The player cannot place objects on top of locked cells. We might want to use the same system for ensuring players cannot place items on top of each other.

A helper method for defining locked zones might be good too. Example: `addLockedZone(0,0,4,4)`. The first two parameters is the start coordinate, the last two is the end coordinate.

**Comment by InDieTasten** [comment]
Scope of isodom? yes/no?

**Comment by Nathix** [comment]
I would say yes since we would be able to add checks on moving objects to see if it's allowed or not. We could also provide some sort of event/callback if a locked zone is blocking the function.

**Comment by InDieTasten** [comment]
i guess we should design the public interface of isodom.js in it's entirety first, rather then opening issues for each function individually. just makes it more complicated to get everything straight and simple to use.

**Comment by InDieTasten** [comment]
The core isodom library will not cover the concrete placement via anything other than the public interface.
The public interface however, will provide functions to enable such mechanics, as can later be seen in the demo examples.
